on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version of release, e.g. v0.1.0"
        required: true

env:
  VERSION:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # set the verion to the input. if not set, it will be the tag name
      - run: echo "VERSION=${{ inputs.version || github.ref_name }}" >> $GITHUB_ENV

      # create the release
      - run: gh release create ${{ env.VERSION }} -t ${{ env.VERSION }} --verify-tag -n "See CHANGELOG.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # upload the artifacts
      - run: gh workflow run upload-artifacts.yaml --field version=${{ env.VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
