on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of release, e.g. v0.1.0"
        required: true

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -C link-arg=-s
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - run: |
          mkdir layer/
          cp target/${{ matrix.target }}/release/aws-lambda-log-filter layer/
          cp scripts/entry.sh layer/
          zip -j aws-lambda-log-filter-${{ inputs.version }}-layer-${{ matrix.target }}.zip layer/*

      - run: gh release delete-asset ${{ inputs.version }} aws-lambda-log-filter-${{ inputs.version }}-layer-${{ matrix.target }}.zip -y || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: gh release upload ${{ inputs.version }} aws-lambda-log-filter-${{ inputs.version }}-layer-${{ matrix.target }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
